version: '3'
services:

  worker:
    build: ./Worker
    image: worker:latest
    deploy:
      mode: replicated
      replicas: 4
    volumes:
      - ./Worker:/Worker
      - 'shared:/Worker/jobs'
      - './Shared:/Worker/jobs'
    networks:
      - net0

  manager:
    build: ./Manager
    container_name: manager
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./Manager:/Manager
      - 'shared:/Manager/jobs'
      - './Shared:/Manager/jobs'
    networks:
      - net0

volumes:
  shared:
    driver: local

networks:
  net0:
    driver : bridge


