version: '3'
services:

  manager:
    ports:
      - '5050:3000'
    build: ./Manager
    image: manager:latest
    container_name: manager
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ./Manager:/Manager
      - 'shared:/Manager/jobs'
      - './Shared:/Manager/jobs'
    networks:
      net0:
        ipv4_address: 172.25.0.14

  worker1:
    build: ./Worker
    image: worker:latest
    container_name: worker1
    volumes:
      - ./Worker:/Worker
      - 'shared:/Worker/jobs'
      - './Shared:/Worker/jobs'
    networks:
      net0:
        ipv4_address: 172.25.0.10

  worker2:
    build: ./Worker
    image: worker:latest
    container_name: worker2
    volumes:
      - ./Worker:/Worker
      - 'shared:/Worker/jobs'
      - './Shared:/Worker/jobs'
    networks:
      net0:
        ipv4_address: 172.25.0.11

  worker3:
    build: ./Worker
    image: worker:latest
    container_name: worker3
    volumes:
      - ./Worker:/Worker
      - 'shared:/Worker/jobs'
      - './Shared:/Worker/jobs'
    networks:
      net0:
        ipv4_address: 172.25.0.12
  
  worker4:
    build: ./Worker
    image: worker:latest
    container_name: worker4
    volumes:
      - ./Worker:/Worker
      - 'shared:/Worker/jobs'
      - './Shared:/Worker/jobs'
    networks:
      net0:
        ipv4_address: 172.25.0.13

volumes:
  shared:
    driver: local

networks:
  net0:
    driver : bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16


